# Generated by Django 5.0.3 on 2024-06-10 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=64, null=True)),
                ('software_id', models.CharField(max_length=64, null=True)),
                ('license_type', models.CharField(choices=[('L', 'Lease'), ('W', 'Warranty'), ('M', 'Maintenance')], max_length=64, null=True)),
                ('contact_status', models.CharField(choices=[('ACT', 'Active'), ('PEN', 'Pending'), ('DIS', 'In-Active')], max_length=64, null=True)),
                ('renewal_status', models.CharField(choices=[('ACT', 'Active'), ('PEN', 'Pending'), ('DIS', 'In-Active')], max_length=64, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('added', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('software_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('software_name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('PEN', 'Pending'), ('DIS', 'In-Active')], max_length=64, null=True)),
                ('category', models.CharField(choices=[('SS', 'System'), ('APP', 'Application'), ('MID', 'Middleware'), ('OF', 'Office')], max_length=64, null=True)),
                ('contract_value', models.FloatField(blank=True, null=True)),
                ('number_of_licenses', models.FloatField(blank=True, null=True)),
                ('managed_by', models.CharField(max_length=64, null=True)),
                ('software_type', models.CharField(choices=[('OP', 'On-platform'), ('C', 'Cloud')], max_length=64, null=True)),
                ('vendor', models.CharField(max_length=64, null=True)),
                ('number_of_users', models.FloatField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('employee_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('department', models.CharField(choices=[('FIN', 'Finance'), ('HR', 'Human Resources'), ('IT', 'Technical Support')], max_length=64, null=True)),
                ('position', models.CharField(max_length=64, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.DateTimeField(blank=True, null=True)),
                ('software_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sam.software')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sam.staff')),
            ],
        ),
    ]
